### ISSUE TITLE
Capture the request and response to store in a file

### ISSUE THREAD

**Issue by santhoshTpixler** [kr/mitm#5]
I want to capture both HTTP and HTTPS requests. The captured request and response should be stored in a file. I came across this project. I was able to use it as a proxy server, but how do I capture the request and response. I am new to go, is there any example provided? 

Thanks

**Comment by kr** [comment]
You might want to look at [httputil.DumpRequestOut](https://golang.org/pkg/net/http/httputil/#DumpRequestOut) and [httputil.DumpResponse](https://golang.org/pkg/net/http/httputil/#DumpResponse) — I bet those will help!

**Comment by santhoshTpixler** [comment]
It helped me well. But for response capturing, I have only `http.ResponseWriter`

**Comment by kr** [comment]
Ah, true. You might be able to use [httptest.ResponseRecorder](https://golang.org/pkg/net/http/httptest/#ResponseRecorder) to make a second ResponseWriter, and provide that to the upstream handler to capture the response. Then you could use its [Result](https://golang.org/pkg/net/http/httptest/#ResponseRecorder.Result) method to dump the result.

You'll probably also have to write some code to copy the result data from the ResponseRecorder to the original ResponseWriter that goes to the client.

Note that this will mean collecting the entire response in memory. If it's a big response, that'll take a lot of memory and the client will have to wait longer for the response. If that's not okay, then you could instead make your own wrapper type for the ResponseWriter that streams the response, bit by bit, to both the client and to the file. That would mean writing significantly more code.

Finally, you should use [httputil.DumpRequest](https://golang.org/pkg/net/http/httputil/#DumpRequest) instead of DumpRequestOut. Sorry for the wrong advice before.

**Comment by santhoshTpixler** [comment]
@kr  Got it. Thank you for your valuable support.

**Comment by santhoshTpixler** [comment]
@kr HTTPS requests are proxied as expected. But HTTP requests are getting timed out. Any idea on how to fix it?

**Comment by kr** [comment]
For plaintext http, I'd suggest bypassing this package altogether. There should be no need for mitm in that case.

**Comment by brydavis** [comment]
Use a multi-writer to write bytes to multiple readers.

Standard output used here, but you could add / replace it with a file, etc.

	m := io.MultiWriter(
		w.ResponseWriter,
		os.Stdout,
	)

	m.Write([]byte("some data..."))
